### ISSUE TITLE
smpl模型输出得到的6890个vertices顶点如何得到对应的眼睛的2d关键点的图像坐标？

### ISSUE THREAD

**Issue by APeiZou** [caizhongang/humman_toolbox#1]
@caizhongang    hello， visualizer.py代码里面输出的smpl模型输出得到的6890个proj_vertices顶点如何得到对应的眼睛或者鼻子等的2d关键点的图像坐标？
proj_vertices = perspective_projection(vertices, K, R, T)     
# draw on the color image
proj_vertices = np.round(proj_vertices).astype(int).tolist()
for point in proj_vertices:
    color = cv2.circle(color, tuple(point), 1, (255, 255, 255), thickness=-1)

**Comment by caizhongang** [comment]
你好，

SMPL 和 SMPL-H 定义了一些身体表面点，其vertex id可以在[这里](https://github.com/vchoutas/smplx/blob/main/smplx/vertex_ids.py#L25-L29)找到：

```
{
        'nose':		    332,  # 鼻子
        'reye':		    6260,  # 右眼
        'leye':		    2800,  # 左眼
        'rear':		    4071,  # 右耳
        'lear':		    583  # 左耳
}
```

可以通过`perspective_projection`只投影相应的点来获取它们的2D坐标，例如：

```
proj_vertices = perspective_projection(vertices[[332, 6260, 2800, 4071, 583]], K, R, T)
```

**Comment by APeiZou** [comment]
@caizhongang 谢谢，非常感谢您得回复， 姿态得标注文件有开源得计划吗？

**Comment by caizhongang** [comment]
有的，更多子集（subset）会在几个月内陆续开源，敬请期待！

**Comment by APeiZou** [comment]
@caizhongang 好的，感谢你们发布得优秀得工作，谢谢。
