### ISSUE TITLE
render problem

### ISSUE THREAD

**Issue by MrLi333** [caizhongang/humman_toolbox#10]
I want to use pyrender to get the projection result, but I found a problem using the camera parameters, can you help? How to use pyrender for projection？

**Comment by caizhongang** [comment]
Hi @MrLi333 , this [tool](https://github.com/caizhongang/gta-human_toolbox/tree/main/gta-human_v2#run-2d-visualizer) we developed for GTA-Human (another human-centric dataset) is implemented with PyRender. It may be helpful to you.
