### ISSUE TITLE
About the release of Motion Generation Subset

### ISSUE THREAD

**Issue by Infinitywxh** [caizhongang/humman_toolbox#11]
Thanks the authors for the great work! I wonder when the Motion Generation Subset will be released?

**Comment by caizhongang** [comment]
Hi @Infinitywxh , the HuMMan-MoGen has been released in `humman_mogen/`.

**Comment by Infinitywxh** [comment]
Thanks for the prompt reply!

**Comment by GuangtaoLyu** [comment]
how to get the action label list?
