### ISSUE TITLE
a link of the depth picture

### ISSUE THREAD

**Issue by hengyu-wang** [caizhongang/humman_toolbox#15]
Hello, can you give me a link of the depth picture？Thank you!

**Comment by caizhongang** [comment]
Hi @hengyu-wang , we have included the download links for [HuMMan-Recon](https://github.com/caizhongang/humman_toolbox/tree/main/humman_recon#downloads) and [HuMMan-Point](https://github.com/caizhongang/humman_toolbox/tree/main/humman_point#downloads).

HuMMan-Recon contains 1 file for depth images, HuMMan-Point contains 11 files. 

Hope this helps!

**Comment by hengyu-wang** [comment]
> Hi @hengyu-wang , we have included the download links for [HuMMan-Recon](https://github.com/caizhongang/humman_toolbox/tree/main/humman_recon#downloads) and [HuMMan-Point](https://github.com/caizhongang/humman_toolbox/tree/main/humman_point#downloads).
> 
> HuMMan-Recon contains 1 file for depth images, HuMMan-Point contains 11 files.
> 
> Hope this helps!

I get it,thanks!
