### ISSUE TITLE
Issue about Calibration

### ISSUE THREAD

**Issue by Chen3110** [caizhongang/humman_toolbox#2]
Hello,

I'm using the HuMMan dataset and I try to project the skeleton keypoints obtained from SMPL onto Kinect color images. However, I noticed that the projected 2D keypoints do not match with the image. It appears that the depth coordinates are flipped. Could you please let me know what might be going wrong? 

I'm using the following conversion formula: Jworld = R @ Jcam + T, where J is the coordinates of 3D joints, R is the rotation matrix R from camera.json, and T is the translation vector T.

Thank you for your help.

**Comment by caizhongang** [comment]
Hi @Chen3110 ,

Please note that the transformation convention in HuMMan is **world2cam**.

More details can be found [here](https://github.com/caizhongang/humman_toolbox#camerasjson).

You may also use our simple visualizer to verify.

Hope this helps!

**Comment by Chen3110** [comment]
Wow! I get it! Thank you so much!

**Comment by caizhongang** [comment]
I'll close the issue if it's resolved :)
