### ISSUE TITLE
about fps

### ISSUE THREAD

**Issue by shaohua-pan** [caizhongang/humman_toolbox#3]
Hello,

What is the sequences fps?

Thank you for your help.

**Comment by caizhongang** [comment]
Hi @isshpan ,

The original videos were taken at 30 fps.  

To reduce the amount of data in the Reconstruction Subset, we downsample all videos to 5 fps. The original frame IDs are kept, so all images have frame IDs divisible by 6 (e.g., 000000.png, 000006.png ...).

Future subsets for other tasks may have different downsample ratios. Please stay tuned :)

Hope this helps.
