### ISSUE TITLE
Action label

### ISSUE THREAD

**Issue by qiqiApink** [caizhongang/humman_toolbox#4]
Can you provide the action label for each sequence?

**Comment by caizhongang** [comment]
Hi @qiqiApink ,

Currently we have just released the Reconstruction Subset, which is not designed for action recognition as it does not contain many clips. There will be an Action Understanding Subset that may better suit your research direction, and we hope to release it in a couple of months.

For now, if you would like to get the action label, you may refer to the name of the sequence which contains the person ID and action ID (e.g., pxxxxxx_axxxxxx, where 'p' for person and 'a' for action). The complete list of actions may be found [here](https://docs.google.com/spreadsheets/d/1-DoRVZskJgYo8SFxZs6qkzdsrppF9W09md8U6YpBHsk/edit?usp=sharing).

Hope this helps!
