### ISSUE TITLE
about depth images

### ISSUE THREAD

**Issue by XinyingZheng** [caizhongang/humman_toolbox#5]
大佬，深度数据什么时候释放呀

**Comment by caizhongang** [comment]
@XinyingZheng 你好！

在重建子集发布之后，我们会在今年上半年再发布两个子集：行动理解子集和感知子集。其中感知子集将包括深度数据，同时我们也将同时发布重建子集的深度数据。我们预计深度数据将在今年上半年内的几个月内发布。

不介意的话也请在这个[Google Form](https://forms.gle/aBL4yTMo2zL3p9P69)注册，我们在发布数据的第一时间会通知所有注册用户。
