### ISSUE TITLE
Depth Image

### ISSUE THREAD

**Issue by zhangquanchen** [caizhongang/humman_toolbox#8]
Hi, it seems that the url is out-of-date and can't get the download path of "depth images". Would you mind providing the download path for "depth image" again? Thanks！

**Comment by caizhongang** [comment]
Hi @Jankin66 , we are changing our data storage host, the new links will be updated shortly (likely by this weekend). Sorry for the confusion and please stay tuned!

**Comment by zhangquanchen** [comment]
ok, thanks so much

**Comment by zhangquanchen** [comment]
hi, sorry for bothering you. We still haven't seen the correct links, thank you!

**Comment by caizhongang** [comment]
Hi, we are still working on the host site for our data. In the meantime, the data could be downloaded from our temporary site [here ](https://openxlab.org.cn/datasets/OpenXDLab/HuMMan/tree/main/humman_release_v1.0_recon), where `recon_kinect_depth.zip` will be the depth images.

**Comment by zhangquanchen** [comment]
get it! thank you so much!

**Comment by zhangquanchen** [comment]
已收到您的信件！
